config/routes.rb
Rails.application.routes.draw do
  resources :volumes
  resources :companies, only: [:edit, :update, :show]
  resources :journals do
    patch 'combine_pdfs'
  end
  resources :articles do
    patch 'update_users_article'
    patch 'update_correction_note'
  end
  root to: 'visitors#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users
  resources :visitors, only: [:index]

  get 'iframe', to: 'visitors#iframe'
  #get 'statistics', to: 'visitors#statistics'
  resources :statistics, only: [:index]

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :journal

  #belongs_to :referee_1, class_name: 'User'
  #belongs_to :referee_2, class_name: 'User'
  #belongs_to :referee_3, class_name: 'User'

  belongs_to :tmdcm_1, class_name: 'User'
  belongs_to :tmdcm_2, class_name: 'User'


  has_many :users_articles, class_name: 'UsersArticle'
  has_many :reviewed_users, through: :users_articles, source: :user
  has_many :referee_reviewed_users, -> {where role: :referee}, through: :users_articles, source: :user
  has_many :ecm_reviewed_users, -> {where role: :ecm}, through: :users_articles, source: :user

  has_one :selected_referee, dependent: :destroy
  accepts_nested_attributes_for :selected_referee

  default_scope {order('status DESC')}

  dragonfly_accessor :file

  before_create :build_referee

  after_save :send_email
  #after_update :set_referee_assigned_date


  after_update :check_corrected

  # eca: editorial comitee approved, to correct by editorial comitee, to correct by referres
  enum status: [:basic, :rejected, :eca, :tcbec, :pending_review, :approved_by_referees, :tcbr, :approved, :assigned_journal, :published]

  enum kind: [:review, :paper, :brief_communication, :comment]

  validates :title, presence: :true
  validates :abstract, presence: :true
  validates :language, presence: :true
  validates :file, presence: :true


  def title_and_key_words
    String(title) + ' (' + String(key_words) + ' )'
  end

  def update_users_article(user, article_status, note, referee_1_id, referee_2_id, referee_3_id)

    user_article = UsersArticle.new(user: user, article: self, status: article_status, correction_note: note,
                                    referee_1_id: referee_1_id, referee_2_id: referee_2_id, referee_3_id: referee_3_id)

    users_articles << user_article

    # count editorial comitee

    ac = 0
    rc = 0
    dc = 0

    if basic?
      users_articles.each do |ua|
        ac += 1 if ua.eca?
        rc += 1 if ua.rejected_by_ec?
        dc += 1 if ua.tcbec?
      end

      if ecm_reviewed_users.count == 3 && ac + dc > rc && ac > dc
        update_attribute(:status, :eca)

      elsif ecm_reviewed_users.count == 3 && ac + dc > rc && ac <= dc
        update_attribute(:status, :tcbec)

      elsif ecm_reviewed_users.count == 3 && ac + dc <= rc
        update_attribute(:status, :rejected)
      end


      # count referees members
    elsif eca?
      users_articles.each do |ua|
        ac += 1 if ua.approved_by_referee?
        rc += 1 if ua.rejected_by_r?
        dc += 1 if ua.tcbr?
      end

      if referee_reviewed_users.count == 3 && ac + dc > rc && ac > dc
        update_attribute(:status, :approved)
      elsif referee_reviewed_users.count == 3 && ac + dc > rc && ac <= dc
        update_attribute(:status, :tcbr)
      elsif referee_reviewed_users.count == 3 && ac + dc <= rc
        update_attribute(:status, :rejected)
      end

    end


  end


  def suggested_referees
    referees = []
    users_articles.each do |ua|
      referees << ua.referee_1
      referees << ua.referee_2
      referees << ua.referee_3
    end

    referees.uniq.compact

  end

  def selected_referees
    [selected_referee&.referee_1, selected_referee&.referee_2, selected_referee&.referee_3]
  end


  private

  def send_email
    if basic? || approved? || rejected? || tcbec? || published?
      UserMailer.article_email(user, self).deliver_later
    end
  end


  def set_referee_assigned_date
    if saved_change_to_referee_1_id? || saved_change_to_referee_2_id? || saved_change_to_referee_3_id?

      update_attribute(:referee_assigned_date, Date.today)
      #self.referee_assigned_date = Date.today
    end
  end


  def check_corrected
    if tcbec? && checked_as_corrected
      update_attributes(checked_as_corrected: false, status: :basic)
      users_articles.each do |ua|
        if ua.user.role == "ecm"
          ua.destroy
        end
      end
    elsif tcbr? && checked_as_corrected
      update_attributes(checked_as_corrected: false, status: :eca)
      users_articles.each do |ua|
        if ua.user.role == "referee"
          ua.destroy
        end
      end
    end


  end


  def build_referee
    build_selected_referee
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json {head :forbidden, content_type: 'text/html'}
      format.html {
        flash[:danger] = exception.message
        redirect_to root_path
      }
      format.js {head :forbidden, content_type: 'text/html'}
    end
  end


  before_action :authenticate_user!
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /articles
  # GET /articles.json
  def index

    if current_user.basic? || current_user.adviser?
      @articles = current_user.articles
    elsif current_user.ecm?
      @articles = Article.where(status: :basic)
    elsif current_user.referee?
      @articles = Article.joins(:selected_referee).where('selected_referees.referee_1_id = ?', current_user.id).or(Article.joins(:selected_referee).where('selected_referees.referee_2_id = ?', current_user.id)).or(Article.joins(:selected_referee).where('selected_referees.referee_3_id = ?', current_user.id))
    elsif current_user.tmdcm?
      @articles = Article.where(status: :approved)
    elsif current_user.director? || current_user.admin?
      @articles = Article.all
    else
      @articles = []
    end


    #@articles = Article.all

  end

  # GET /articles/1
  # GET /articles/1.json
  def show

    #redirect_to '/web/viewer.html?file='+ current_user.name
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    respond_to do |format|
      if @article.save
        format.html {redirect_to @article, notice: '¡El artículo fue creado con éxito!'}
        format.json {render :show, status: :created, location: @article}
      else
        format.html {render :new}
        format.json {render json: @article.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update

    @journal = @article.journal

    respond_to do |format|
      #if @article.update(article_params.merge(user_id: current_user.id))
      if @article.update(article_params)
        @journal = @article.journal if @article.journal
        format.html {redirect_to @article, notice: '¡El artículo fue editado con éxito!'}
        format.js {}
        format.json {render :show, status: :ok, location: @article}
      else
        format.html {render :edit}
        format.json {render json: @article.errors, status: :unprocessable_entity}
        format.js {}
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html {redirect_to articles_url, notice: '¡El artículo fue eliminado con éxito!'}
      format.json {head :no_content}
    end
  end


  # PATCH articles/:article_id/update_users_article
  def update_users_article
    @article = Article.find(params[:article_id])

    @article.update_users_article(current_user, params[:status], params[:note], params[:referee_1_id],
                                  params[:referee_2_id], params[:referee_3_id])

    respond_to do |format|
      format.html {redirect_to @article, notice: '¡El artículo fue actualizado con éxito!.'}
    end

  end

  def update_correction_note
    @article = Article.find(params[:article_id])
    @users_article = UsersArticle.find(params[:users_article_id])
    @users_article.update_attributes(correction_note: params[:correction_note], checked_by_director: true)

    respond_to do |format|
      format.html {redirect_to @article, notice: '¡Revision enviada con éxito!'}
    end

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.require(:article).permit(:title, :abstract, :author, :kind, :status, :file, :position, :journal_id, :key_words,
                                    :referee_1_id, :referee_2_id, :referee_3_id, :tmdcm_1_id, :tmdcm_2_id,
                                    :tmdcm_1_review, :tmdcm_2_review, :checked_as_corrected, :language,
                                    selected_referee_attributes: [:id, :referee_1_id, :referee_2_id, :referee_3_id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :abstract %>
      <%= f.input :author %>
      <%= f.input :key_words %>
      <%= f.input :language %>

      <%= f.input :kind, collection: Article.kinds.keys.map {|role|
        [t(role, scope: [:activerecord, :attributes, :article, :kinds]), role]}, include_blank: false %>

      <% if current_user.admin? %>
          <%= f.input :status, collection: Article.statuses.keys.map {|role|
            [t(role, scope: [:activerecord, :attributes, :article, :status]), role]}, include_blank: false %>
      <% end %>

      <% if current_user.id == @article&.user&.id && (@article&.tcbec? || @article&.tcbr? )   %>
              <%= f.input :checked_as_corrected %>
      <% end %>

      <%= f.input :file, as: :file, input_html: {accept:'.pdf'} %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: 'btn btn-block btn-primary' %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editar artículo</h1>

<%= render 'form', article: @article %>

<hr>

<%= link_to 'Ver', @article, class: 'btn  btn-info' %>
<%= link_to 'Volver', articles_path, class: 'btn  btn-info' %>

app/views/articles/index.html.erb
<div class="d-block mx-auto" style="">

<% if (current_user.admin? || current_user.director?) %>
  <h1>Artículos Registrados en el Sistema</h1>
  <% elsif current_user.basic? || current_user.adviser? %>
    <h1>Mis Artículos</h1>
  <% else%>
    <h1>Artículos</h1>
<% end %>
  
  

  <table class="table table-hover">
    <thead>
    <tr>
      <th>Título</th>
      <th>Tipo</th>
      <th>Autores</th>
      <th>Estado</th>
      <th>Número</th>
      <th colspan="3">Opciones</th>
    </tr>
    </thead>

    <tbody>
    <% @articles.each do |article| %>
        <tr>
          <td><%= article.title %></td>
          <td><%= t(article.kind, scope: [:activerecord, :attributes, :article, :kinds] ) %></td>
          <td><%= article.author %></td>
          <td><%= t(article.status, scope: [:activerecord, :attributes, :article, :status]) %></td>
          <td>
            <%= if article.published? || article.assigned_journal?
                 "N°" + article&.journal&.volume&.number.to_s + "-" + "Vol." +article&.journal&.identifier.to_s
                end %>
          </td>
          <td><%= link_to '', article, class: 'fa fa-eye' %></td>

          <% if (article.user == current_user && (article.tcbec? || article.tcbr?)) || current_user.admin? %>
              <td><%= link_to '', edit_article_path(article), class: 'fa fa-pencil' %></td>
          <% end %>

          <% if current_user.director? && article.rejected? || current_user.admin? %>
              <td><%= link_to '', article, method: :delete, data: {confirm: '¿Estás seguro?'}, class: 'fa fa-trash' %></td>
          <% end %>

        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Enviar artículo nuevo', new_article_path, class: 'btn btn-primary' %>
</div>

app/views/articles/new.html.erb
<h1>Nuevo artículo</h1>

<%= render 'form', article: @article %>

<hr>

<%= link_to 'Volver', articles_path, class: 'btn  btn-info' %>

app/views/articles/show.html.erb
<div class="container-with-margin">


  <!-- Editorial comitee member -->
  <% if current_user.ecm? && !current_user.reviewed_article?(@article) && @article.basic? %>

      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Opciones de aprobación</h4>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item fa "> &nbsp;

            <!-- Approved -->
            <%= simple_form_for @article, url: article_update_users_article_path(@article) do |f| %>

                <%= hidden_field_tag :status, :eca %>

                Selccione al primer árbitro:
                <%= select_tag :referee_1_id, options_from_collection_for_select(User.where(role: :referee), 'id', 'first_name_and_speciality') %>
                <br><br>
                Selccione al segundo árbitro:
                <%= select_tag :referee_2_id, options_from_collection_for_select(User.where(role: :referee), 'id', 'first_name_and_speciality') %>
                <br><br>
                Selccione al tercer árbitro:
                <%= select_tag :referee_3_id, options_from_collection_for_select(User.where(role: :referee), 'id', 'first_name_and_speciality') %>
                <br><br>

                &nbsp; &nbsp;


                <%= f.submit 'Aprobar', class: 'btn btn-primary btn-block' %>

            <% end %>
          </li>

          <li class="list-group-item fa "> &nbsp;

            <!-- Rejected -->
            <%= simple_form_for @article, url: article_update_users_article_path(@article) do |f| %>

                <%= hidden_field_tag :status, :rejected_by_ec %>
                Escriba el motivo del rechazo: <br>
                <%= text_field_tag :note %>

                &nbsp; &nbsp;


                <%= f.submit 'Rechazar', class: 'btn btn-danger' %>

            <% end %>

          </li>

          <li class="list-group-item fa "> &nbsp;

            <!-- correction note -->
            <%= simple_form_for @article, url: article_update_users_article_path(@article) do |f| %>

                <%= hidden_field_tag :status, :tcbec %>
				Escriba la corrección correspondiente: <br>
                <%= text_field_tag :note %>

                &nbsp; &nbsp;

                <%= f.submit 'Enviar correción', class: 'btn btn-info' %>

            <% end %>
          </li>
        </ul>
      </div>

      <br>
      <br>
      <br>
      <br>


  <% end %>



  <!-- Referees members -->
  <% if current_user.referee? && !current_user.reviewed_article?(@article) && @article.eca? && @article.selected_referees.include?(current_user) %>

      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Opciones de revisión</h4>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item fa "> &nbsp;


            <!-- Approved -->
            <%= simple_form_for @article, url: article_update_users_article_path(@article) do |f| %>

                <%= hidden_field_tag :status, :approved_by_referee %>

                &nbsp;&nbsp;
                <%= f.submit 'Aprobar', class: 'btn btn-primary' %>

            <% end %>

          </li>

          <li class="list-group-item fa "> &nbsp;

            <!-- Rejected -->
            <%= simple_form_for @article, url: article_update_users_article_path(@article) do |f| %>

                <%= hidden_field_tag :status, :rejected_by_r %>
                <%= text_field_tag :note %>

                &nbsp;&nbsp;

                <%= f.submit 'Rechazar', class: 'btn btn-danger' %>

            <% end %>
          </li>

          <li class="list-group-item fa "> &nbsp;

            <!-- -->
            <%= simple_form_for @article, url: article_update_users_article_path(@article) do |f| %>

                <%= hidden_field_tag :status, :tcbr %>
                <%= text_field_tag :note %>

                &nbsp;&nbsp;
                <%= f.submit 'Enviar correción', class: 'btn btn-info' %>

            <% end %>
          </li>
        </ul>
      </div>


      <br><br>

  <% end %>


  <!-- Director -->
  <% if current_user.director? && @article.eca? && (!@article&.selected_referee.referee_1 || !@article&.selected_referee.referee_2 || !@article&.selected_referee.referee_3) %>

      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Selección de árbitros</h4>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item fa "> &nbsp;


            <%= simple_form_for @article do |f| %>

                <%= f.simple_fields_for :selected_referee do |sr| %>
                    <% unless @article&.selected_referee.referee_1_id %>
                    	Selccione al primer árbitro:
                        <%= sr.select :referee_1_id, @article.suggested_referees.map {|u| [u&.first_name_and_speciality, u&.id]} %>
                    <% end %>
                    <br> <br>

                    <% unless @article&.selected_referee.referee_2_id %>
                    	Selccione al segundo árbitro:
                        <%= sr.select :referee_2_id, @article.suggested_referees.map {|u| [u&.first_name_and_speciality, u&.id]} %>
                    <% end %>
                    <br> <br>
                    <% unless @article&.selected_referee.referee_3_id %>
                    	Selccione al tercer árbitro:
                        <%= sr.select :referee_3_id, @article.suggested_referees.map {|u| [u&.first_name_and_speciality, u&.id]} %>
                    <% end %>

                <% end %>

                &nbsp; &nbsp;
                <br> <br>
                <%= f.submit 'Enviar a los arbitros', class: 'btn btn-primary btn-block', data: {confirm: '¿Estás seguro que quieres enviar a los arbitros?'} %>

                </li>

            <% end %>
            </ul>
      </div>

      <br><br>

  <% end %>

  <!-- Visto bueno -->
  <% if current_user.tmdcm? && @article.approved? %>

      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Revisión de artículo</h4>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item fa "> &nbsp;


            <%= simple_form_for @article do |f| %>

                <% if @article.tmdcm_1.nil? && current_user != @article.tmdcm_2 %>
                    <%= f.input :tmdcm_1_review, include_blank: false %>

                    <%= f.hidden_field :tmdcm_1_id, value: current_user.id %>

                    &nbsp;&nbsp;
                    <%= f.submit 'Enviar', class: 'btn btn-primary btn-block' %>


                <% elsif @article.tmdcm_2.nil? && current_user != @article.tmdcm_1 %>

                    <%= f.input :tmdcm_2_review, include_blank: false %>

                    <%= f.hidden_field :tmdcm_2_id, value: current_user.id %>

                    &nbsp;&nbsp;
                    <%= f.submit 'Enviar', class: 'btn btn-primary btn-block' %>

                <% end %>

                </li>


            <% end %>
            </ul>
      </div>

      <br><br>

  <% end %>


  <% if false %>

      <% if @article.basic? %>
          <%= link_to "Aprobar <span class='glyphicon glyphicon-ok'></span>".html_safe, article_path(id: @article.id, article: {status: :approved}), method: :patch, remote: false, class: 'btn btn-primary' %>
      <% else %>
          <%= link_to "Aprobar <span class='glyphicon glyphicon-ok'></span>".html_safe, article_path(id: @article.id, article: {status: :approved}), method: :patch, remote: false, class: 'btn btn-primary' %>
      <% end %>

  <% end %>

<!-- Director or Admin-->
  <% if current_user.director? || current_user.admin? %>

      <div class="card">
        <div class="card-body">
        <h4 class="card-title">Revisiones del Comité Editorial</h4>

          <% @article.users_articles.each do |ua| %>

              <% if ua.user.role == "ecm" %>

                  <%= ua.user.first_name %> :

                  <%= t(ua.status, scope: [:activerecord, :attributes, :users_article, :status]) %>
                  <br>
              <% end %>

          <% end %>

        </div>
      </div>


      <div class="card">
        <div class="card-body">
         <h4 class="card-title">Revisiones del Arbitraje</h4>

          <% @article.users_articles.each do |ua| %>

              <% if ua.user.role == "referee" %>

                  <%= ua.user.first_name %> :

                  <%= t(ua.status, scope: [:activerecord, :attributes, :users_article, :status]) %>
                  <br>
              <% end %>

          <% end %>

        </div>
      </div>
      <br><br>
  <% end %>




  <div class="card">
    <div class="card-body">
      <h4 class="card-title"><%= @article.title %></h4>
      <p class="card-text"><%= @article.abstract %></p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item fa fa-user"> &nbsp; <%= @article.author %></li>
      <li class="list-group-item fa fa-info-circle"> &nbsp; <%= t(@article.status, scope: [:activerecord, :attributes, :article, :status]) %></li>

      <li class="list-group-item fa fa-book"> &nbsp; <%= t(@article.kind, scope: [:activerecord, :attributes, :article, :kinds] ) %></li>

      <li class="list-group-item fa fa-key"> &nbsp; <%= @article.key_words %></li>

      <li class="list-group-item fa fa-globe"> &nbsp; <%= @article.language %></li>

      <% @article.users_articles.each do |ua| %>
          <% if ua.correction_note && !ua.correction_note.empty? && (ua.user.ecm? || ua.checked_by_director?) %>
              <li class="list-group-item ">
                <span class="fa fa-comment">&nbsp;<%= ua.correction_note %></span>
                <br>
                <!--<span class="fa fa-user">&nbsp;<%#= ua.user.role %></span>-->
              </li>
          <% end %>

          <% if ua.correction_note && current_user.director? && ua.user.referee? && !ua.checked_by_director %>
              Correción pendiente: <br>
              <%= simple_form_for @article, url: article_update_correction_note_path(@article, users_article_id: ua.id) do |f| %>

                  <%= text_area_tag :correction_note, ua.correction_note %>

                  <%= f.submit 'Enviar correción', class: 'btn btn-info' %>

              <% end %>
          <% end %>

      <% end %>
      <% if (current_user.director? || current_user.admin?) && (@article.tmdcm_1_review? || @article.tmdcm_2_review?) %>
          <li class="list-group-item fa fa-check-circle"> &nbsp; Visto Bueno</li>

      <% end %>

      <!--<li class="list-group-item "> &nbsp; <%#= link_to ' Edit', edit_article_path(@article), class: "fa fa-pencil" %> </li>-->

      <li class="list-group-item "> &nbsp; <%= link_to ' Volver', articles_path, class: "fa fa-chevron-left btn btn-primary btn-block" %> </li>
    </ul>


  </div>

  <br>
  <hr>

  <%= link_to ' Ver en el Navegador', @article&.file&.url, class: "fa fa-paperclip btn btn-primary btn-block" %>


  <!--
  <p>
    <strong>Title:</strong>
    <%#= @article.title %>
  </p>

  <p>
    <strong>Abstract:</strong>
    <%#= @article.abstract %>
  </p>

  <p>
    <strong>Author:</strong>
    <%#= @article.author %>
  </p>

  <p>
    <strong>Status:</strong>
    <%#= @article.status %>
  </p>

  <p>
    <strong>File:</strong>
    <%#= link_to 'Ver en el Navegador', @article&.file&.url %>
    <%#= link_to 'Ver en el Navegador', @article&.file&.remote_url %>

  </p>

  <p>
    <strong>User:</strong>
    <%#= @article&.user&.first_name %>
  </p>


  <iframe src='/web/viewer.html?file=<%#= @article&.file&.remote_url %>' class="article-pdf-viewer"></iframe>


  <hr>

-->

  <br><br>
  <h4>Vista previa</h4>
  <hr>
  <br>

  <iframe src='/web/viewer.html?file=<%= @article&.file&.remote_url %>' class="article-pdf-viewer"></iframe>


  <%#= link_to 'Edit', edit_article_path(@article) %>
  <%#= link_to 'Back', articles_path %>


</div>


<% if false %>

    <canvas id="the-canvas"></canvas>


    <%= javascript_include_tag '/pdf.js' %>


    <script type="text/javascript">

        PDFJS.workerSrc = "/pdf.worker.js";


        var url = '<%= @article&.file&.url %>';

        // Asynchronous download PDF
        PDFJS.getDocument(url)
            .then(function (pdf) {
                return pdf.getPage(1);
            })
            .then(function (page) {
// Set scale (zoom) level
                var scale = 1.5;

// Get viewport (dimensions)
                var viewport = page.getViewport(scale);

// Get canvas#the-canvas
                var canvas = document.getElementById('the-canvas');

// Fetch canvas' 2d context
                var context = canvas.getContext('2d');

// Set dimensions to Canvas
                canvas.height = viewport.height;
                canvas.width = viewport.width;

// Prepare object needed by render method
                var renderContext = {
                    canvasContext: context,
                    viewport: viewport
                };

// Render PDF page
                page.render(renderContext);
            });
    </script>

<% end %>

app/views/articles/update.js.erb
$('#journal-articles').html("<%= escape_javascript(render 'journals/articles', journal: @journal) %>")

if ($('#journal_id').length) {
    combine_pdfs();
}