config/routes.rb
Rails.application.routes.draw do
  resources :volumes
  resources :companies, only: [:edit, :update, :show]
  resources :journals do
    patch 'combine_pdfs'
  end
  resources :articles do
    patch 'update_users_article'
    patch 'update_correction_note'
  end
  root to: 'visitors#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users
  resources :visitors, only: [:index]

  get 'iframe', to: 'visitors#iframe'
  #get 'statistics', to: 'visitors#statistics'
  resources :statistics, only: [:index]

end

app/models/company.rb
class Company < ApplicationRecord


  validates :name, :issn, :electronic_issn, :legal_deposit, presence: :true



end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController


  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json {head :forbidden, content_type: 'text/html'}
      format.html {
        flash[:danger] = exception.message
        redirect_to root_path
      }
      format.js {head :forbidden, content_type: 'text/html'}
    end
  end


  load_and_authorize_resource


  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: '¡La revista ha sido actalizada con éxito!' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :issn, :electronic_issn, :legal_deposit, :creation_date, :indexing)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :issn %>
    <%= f.input :electronic_issn %>
    <%= f.input :legal_deposit %>
    <%= f.input :creation_date %>
    <%= f.input :indexing %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:'btn btn-block btn-primary' %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Configurar revista</h1>

<%= render 'form', company: @company %>

<hr>

<%= link_to 'Ver', @company, class: 'btn btn-info' %>
<%#= link_to 'Volver', companies_path, class: 'btn btn-info' %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Issn</th>
      <th>Electronic issn</th>
      <th>Legal deposit</th>
      <th>Creation date</th>
      <th>Indexing</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.issn %></td>
        <td><%= company.electronic_issn %></td>
        <td><%= company.legal_deposit %></td>
        <td><%= company.creation_date %></td>
        <td><%= company.indexing %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<div class="card">
  <div class="card-body">
    <h4 class="card-title"><%= @company.name %></h4>
    <p class="card-text"><%= @company.issn %></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item fa fa-"> ISSN electrónico:  <%= @company.electronic_issn %></li>
    <li class="list-group-item fa fa-"> Depósito legal:  <%= @company.legal_deposit %></li>
    <li class="list-group-item fa fa-"> Fecha de fundación:  <%= @company.creation_date %></li>
    <li class="list-group-item fa fa-"> Indexación:  <%= @company.indexing %></li>

    <li class="list-group-item">
      <%= link_to 'Editar', edit_company_path(@company), class: 'btn btn-primary btn-block' %>
      <%#= link_to 'Volver', companies_path, class: 'btn btn-info' %>
    </li>

  </ul>


</div>