config/routes.rb
Rails.application.routes.draw do
  resources :volumes
  resources :companies, only: [:edit, :update, :show]
  resources :journals do
    patch 'combine_pdfs'
  end
  resources :articles do
    patch 'update_users_article'
    patch 'update_correction_note'
  end
  root to: 'visitors#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users
  resources :visitors, only: [:index]

  get 'iframe', to: 'visitors#iframe'
  #get 'statistics', to: 'visitors#statistics'
  resources :statistics, only: [:index]

end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user
  belongs_to :volume
  has_many :articles, -> {order(position: :asc)}

  after_update :combine_pdfs
  after_create :combine_pdfs

  after_update :check_published


  enum status: [:basic, :published]

  dragonfly_accessor :cover


  validates :identifier, :editor, :cover, :max_articles, presence: :true



  def combined_pdfs_name
    id.to_s +  '_combined.pdf'
  end

  def combine_pdfs


     #root_name = id.to_s +  '_combined.pdf'

    file_root = Rails.root.join('public') + combined_pdfs_name.to_s

    #puts '+++++++++++++++++'
    #puts file_root
    #puts '+++++++++++++++++'


    File.delete(file_root) if File.exist?(file_root)


    pdf = CombinePDF.new

    if cover
      pdf << CombinePDF.load(Rails.root.join('public').to_s + cover.remote_url)
    end

    articles.each do |a|
      #puts a.title
      pdf << CombinePDF.load(Rails.root.join('public').to_s + a.file.remote_url)
    end

    #root_name = id.to_s +  '_combined.pdf'

    #update_attribute(:file_name, root_name)

    pdf.save(Rails.root.join('public').to_s + '/' + combined_pdfs_name)

  end



  def check_published
    if published?
      articles.each do |a|
        a.update_attribute(:status, :published)
      end
    else
      articles.each do |a|
        a.update_attribute(:status, :assigned_journal)
      end

    end

  end


end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json {head :forbidden, content_type: 'text/html'}
      format.html {
        flash[:danger] = exception.message
        redirect_to root_path
      }
      format.js {head :forbidden, content_type: 'text/html'}
    end
  end


  before_action :authenticate_user!
  before_action :set_journal, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /journals
  # GET /journals.json
  def index

    if params[:term]
      @journals = Journal.where(status: :published).joins(:articles).where('articles.key_words LIKE ? OR articles.title LIKE ? OR articles.author LIKE ?', "%#{params[:term]}%", "%#{params[:term]}%", "%#{params[:term]}%" ).uniq
    else
      if current_user.director? || current_user.admin?
        @journals = Journal.all
      else
        @journals = Journal.where(status: :published)
      end
    end

  end

  # GET /journals/1
  # GET /journals/1.json
  def show
  end

  # GET /journals/new
  def new
    @journal = Journal.new
  end

  # GET /journals/1/edit
  def edit
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = Journal.new(journal_params)

    respond_to do |format|
      if @journal.save
        format.html {redirect_to @journal, notice: '¡El número fue creado con éxito!'}
        format.json {render :show, status: :created, location: @journal}
      else
        format.html {render :new}
        format.json {render json: @journal.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        format.html {redirect_to @journal, notice: '¡El número fue actualizado con éxito!'}
        format.json {render :show, status: :ok, location: @journal}
      else
        format.html {render :edit}
        format.json {render json: @journal.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal.destroy
    respond_to do |format|
      format.html {redirect_to journals_url, notice: '¡El número fue eliminado con éxito!'}
      format.json {head :no_content}
    end
  end


  def combine_pdfs
    @journal = Journal.find(params[:journal_id])


    @journal.combine_pdfs
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_journal
    @journal = Journal.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def journal_params
    params.require(:journal).permit(:identifier, :editor, :publisher, :indexing, :cover, :copyright, :subject, :others, :file_name, :status, :term, :publication_date, :volume_id, :max_articles, article_ids: [])
  end
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/_articles.html.erb
<div class="card">
  <div class="card-body">
    <h4 class="card-title"> Artículos</h4>
    <p class="card-text">Artículos incluidos en este número</p>
  </div>
  <ul class="list-group list-group-flush">


    <% @journal.articles.each do |article| %>

        <li class="list-group-item fa fa-">
          <%= article.title %>   <b><%='(Posición ' + article.position.to_s + ')' %></b>
          <%= link_to ' Ver', article&.file&.url, class: "fa fa-paperclip btn btn-info " %>

          <% unless @journal.published? %>
              <%= link_to "<span class='fa fa-remove'></span>".html_safe, article_path(id: article.id, article: {journal_id: 0, status: :approved}), method: :patch, remote: true, class: 'btn btn-danger', onclick: "" %>
          <% end %>
        </li>

        <br>

    <% end %>

  </ul>

</div>

app/views/journals/_form.html.erb
<%= simple_form_for(@journal) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.association :volume, label_method: :number, value_method: :id, include_blank: false %>
    <%= f.input :identifier %>
    <%= f.input :editor %>
    <%#= f.input :publisher %>
    <%#= f.input :indexing %>
    <%#= f.input :copyright %>
    <%= f.input :subject %>
    <%= f.input :others %>
    <%= f.input :publication_date  %>
    <%= f.input :cover, as: :file, input_html: {accept: '.pdf'} %>
    <%= f.input :max_articles %>

    <% if current_user.admin? %>
        <%= f.input :status, collection: Journal.statuses.keys.map {|role|
          [t(role, scope: [:activerecord, :attributes, :journal, :status]), role]}, include_blank: false %>
    <% end %>

    <%#= f.association :articles, as: :check_boxes  %>
    <%#= f.input :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-block btn-primary' %>
  </div>
<% end %>

app/views/journals/combine_pdfs.js.erb
setTimeout(function () {
    $('#journal-pdfs-preview').html("<iframe src='/web/viewer.html?file=<%= @journal&.combined_pdfs_name %>' class='article-pdf-viewer'></iframe>")
}, 500);

app/views/journals/edit.html.erb
<h1>Editar el Números</h1>

<%= render 'form', journal: @journal %>

<hr>
<%= link_to 'Ver', @journal, class: 'btn b btn-info' %>
<%= link_to 'Volver', journals_path, class: 'btn  btn-info' %>

app/views/journals/index.html.erb
<div class="d-block mx-auto" style="">


  <%= form_tag(journals_path, method: :get) do %>
      <%= text_field_tag :term %>
      <%= submit_tag 'Buscar', class: 'btn  btn-primary' %>
      <%= link_to 'Ver todas', journals_path, class: 'btn  btn-info' %>

  <% end %>


  <hr>

  <h1>Publicaciones</h1>

  <table class="table table-hover">
    <thead>
    <tr>
      <th><%= t('identifier', scope: [:activerecord, :attributes, :journal]) %></th>
      <th>Volumen</th>
      <th>Fecha de publicación</th>
      <th><%= t('subject', scope: [:activerecord, :attributes, :journal]) %></th>
      <th><%= t('status') %></th>
      <th colspan="3">Opciones</th>
    </tr>
    </thead>

    <tbody>
    <% @journals.each do |journal| %>
        <tr>
          <td><%= journal.identifier %></td>
          <td><%= journal.volume&.number %></td>
          <td><%= journal.publication_date %></td>
          <td><%= journal.subject %></td>
          <td><%= t(journal.status) %></td>
          <td><%= link_to '', journal, class: 'fa fa-eye' %></td>
          <% if current_user.director? || current_user.admin? %>
              <td><%= link_to '', edit_journal_path(journal), class: 'fa fa-pencil' %></td>
              <td><%= link_to '', journal, method: :delete, data: {confirm: '¿Estás seguro?'}, class: 'fa fa-trash' %></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <% if current_user.admin? || current_user.director? %>

      <%= link_to 'Crear nuevo número', new_journal_path, class: 'btn btn-primary' %>

  <% end %>

</div>

app/views/journals/new.html.erb
<h1>Crear nuevo Número</h1>

<%= render 'form', journal: @journal %>

<hr>

<%= link_to 'Volver', journals_path, class: 'btn  btn-info' %>

app/views/journals/show.html.erb
<div class="container-with-margin">


  <% if current_user.director? && @journal.articles.count == @journal.max_articles && @journal.basic? %>

      <%= link_to "Publicar <span class='fa fa-send'></span>".html_safe, journal_path(id: @journal.id, journal: {status: :published}), method: :patch, remote: false, class: 'btn btn-primary', data: {confirm: '¿Estás seguro que quieres publicar el número?'} %>

  <% elsif current_user.director? && @journal.articles.count == @journal.max_articles && @journal.published? %>

      <%= link_to "Quitar publicación <span class='fa fa-undo'></span>".html_safe, journal_path(id: @journal.id, journal: {status: :basic}), method: :patch, remote: false, class: 'btn btn-danger', data: {confirm: '¿Estás seguro que quieres quitar la publicación?'} %>


  <% end %>

  <br>
  <br>

  <div class="card">
    <div class="card-body">
      <h4 class="card-title"><%= @journal.identifier %></h4>
      <p class="card-text"><%= @journal.editor %></p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item fa fa-"> <%= t('publisher', scope: [:activerecord, :attributes, :journal]) %>
        : &nbsp; <%= @journal.publisher %></li>


      <li class="list-group-item fa fa-"> <%= t('subject', scope: [:activerecord, :attributes, :journal]) %>
        : &nbsp; <%= @journal.subject %> </li>

      <li class="list-group-item fa fa-"> <%= t('others', scope: [:activerecord, :attributes, :journal]) %>
        : &nbsp; <%= @journal.others %> </li>

      <!--<li class="list-group-item fa fa-"> <%#= t('user')  %>: &nbsp; <%#= @journal.user %> </li>-->

      <li class="list-group-item fa fa-"> Fecha de publicación: &nbsp; <%= @journal.publication_date %> </li>


      <li class="list-group-item fa fa-"> <%= t('status') %>: &nbsp; <%= t(@journal.status, scope: [:activerecord, :attributes, :journal, :status]) %> </li>


      <!--<li class="list-group-item "> &nbsp; <%#= link_to ' Edit', edit_article_path(@article), class: "fa fa-pencil" %> </li>-->

      <li class="list-group-item "> &nbsp; <%= link_to ' Volver ', journals_path, class: " btn btn-primary btn-block fa fa-chevron-left" %> </li>
    </ul>


  </div>

  <br>
  <hr>

  <!-- Important don't remove -->
  <%= hidden_field_tag 'journal', @journal.id, id: 'journal_id' %>
  <!-- --------------------------->


  <% if current_user.admin? || current_user.director? %>
      <% if @journal.articles.count < @journal.max_articles %>
          <%= select_tag 'articles', options_from_collection_for_select(Article.where(status: :approved), 'id', 'title_and_key_words'), id: 'article_id_select' %>
          <%= text_field_tag 'position', '', id: 'article_position_text_field', type: 'number' %>
          <%= button_tag 'Agregar articulo', id: 'add_article_btn', onclick: "addArticleTojournal()" %>

      <% end %>
  <% end %>

  <br>

  <div id='journal-articles'>

    <%= render 'articles', journal: @journal %>

  </div>

  <br>


  <%= link_to 'Ver en el Navegador', "/web/viewer.html?file=" + @journal&.combined_pdfs_name + '?' + Time.now.to_s.parameterize, target: :_blank, class: 'btn btn-block btn-primary' %>


  <br><br>
  <h4>Vista previa</h4>

  <hr>

<%#= button_to 'Generar PDF', journal_combine_pdfs_path(@journal), method: :patch, remote: true %>

  <br>

  <div id="journal-pdfs-preview">

    <iframe src='/web/viewer.html?file=<%= @journal&.combined_pdfs_name.to_s + '?' + Time.now.to_s.parameterize %>' class="article-pdf-viewer"></iframe>

  </div>




  <%#= link_to 'Edit', edit_journal_path(@journal) %>
  <%#= link_to 'Back', journals_path %>


</div>

<script>

    function combine_pdfs() {

        var journalId = $('#journal_id').val();


        $.ajax({
            type: 'PATCH',
            url: '/journals/' + journalId + '/combine_pdfs',
            dataType: 'script',
            data: {
                article: {
                    journal_id: journalId
                }
            }
        }).done(function () {
            location.reload();
        });


    }


    function addArticleTojournal() {
        //console.log('hola');

        var journalId = $('#journal_id').val();
        var articleId = $('#article_id_select').val();
        var position = $('#article_position_text_field').val();

        console.log(articleId, ' ', position);


        $.ajax({
            type: 'PATCH',
            url: '/articles/' + articleId,
            dataType: 'script',
            data: {
                article: {
                    journal_id: journalId,
                    position: position,
                    status: 'assigned_journal'
                }
            }
        }).done(function () {
            combine_pdfs();
        });

    }


</script>