config/routes.rb
Rails.application.routes.draw do
  resources :volumes
  resources :companies, only: [:edit, :update, :show]
  resources :journals do
    patch 'combine_pdfs'
  end
  resources :articles do
    patch 'update_users_article'
    patch 'update_correction_note'
  end
  root to: 'visitors#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :users
  resources :visitors, only: [:index]

  get 'iframe', to: 'visitors#iframe'
  #get 'statistics', to: 'visitors#statistics'
  resources :statistics, only: [:index]

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>


    <ul class="navbar-nav mr-auto">
      <li class="nav-item active ">
        <%= link_to 'Inicio', root_path, class: 'nav-link' %>
      </li>


      <li class="nav-item"><%= link_to 'Artículos', articles_path, class: 'nav-link' %></li>

      <li class="nav-item"><%= link_to 'Números', journals_path, class: 'nav-link' %></li>

    <% if current_user.director? || current_user.admin? %>
        <li class="nav-item"><%= link_to 'Volúmenes', volumes_path, class: 'nav-link' %></li>
    <% end %>

    <% if current_user.director? || current_user.admin? || current_user.ecm? %>
      <li class="nav-item"><%= link_to 'Usuarios', users_path, class: 'nav-link' %></li>
    <% end %>


      <% if current_user.director? || current_user.admin? %>

          <li class="nav-item"><%= link_to 'Estadísticas', statistics_path, class: 'nav-link' %></li>

      <% end %>

    </ul>

    <ul class="navbar-nav ml-auto">

      <% if current_user.admin? || current_user.director? %>

          <% if Company.first %>
              <li class="nav-item"><%= link_to 'Configurar revista', edit_company_path(Company.first), class: 'nav-link' %></li>
          <% end %>
      <% end %>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" herf="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user&.first_name %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

          <ul class="list-unstyled">
            <li class="nav-item"><%= link_to 'Configurar cuenta', edit_user_registration_path, class: 'dropdown-item' %></li>
            <li class="nav-item"><%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
          </ul>

          <% if false %>

              <% if current_user.first_name == 'first_name' %>

                  <a class="dropdown-item" href="#">TEST</a>

              <% elsif current_user.first_name == 'otro_name' %>
                  <%= link_to 'nada', root_path, class: 'dropdown-item' %>
              <% end %>

          <% end %>

        </div>
      </li>
    </ul>



<% else %>

    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Inicio', root_path, class: 'nav-link' %>
      </li>


      <li class="nav-item"><%= link_to 'Iniciar sesión', new_user_session_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link' %></li>

    </ul>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<!--
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%#= image_tag 'logo_ula_2.png', class: 'nav-bar-logo' %> &nbsp;
<%#= link_to 'Home', root_path, class: 'navbar-brand' %>

    </div>
    <div class="collapse navbar-collapse">
      <%#= render 'layouts/navigation_links' %>
<%#= render 'layouts/nav_links_for_auth' %>
    </div>
  </div>
</nav>

-->


<nav class="navbar navbar-expand-lg navbar-light fixed-top " id="mainNav" style="background-color: #27364a;">
  <div class="container">
    <a class="navbar-brand" href= <%= root_path %> >
      <%= image_tag 'logo_ula_2.png', class: 'nav-bar-logo' %>
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa fa-bars" aria-hidden="true"></i>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <%= render 'layouts/nav_links_for_auth' %>


    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= content_for?(:title) ? yield(:title) : "Revista Digital (Carlos Calderon 2017) " %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Revista Digital (Carlos Calderon 2017)" %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <%= render 'layouts/navigation' %>
</header>
<main role="main">
  <br><br><br>
  <%= render 'layouts/messages' %>
  <div class="container">
    <br><br>
    <%= yield %>
  </div>
</main>
</body>
</html>